language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
- pip install -e .

# Command to run tests, e.g. python setup.py test
script: py.test --verbose --capture=no

env:
  global:
    secure: Gj8xD3MdDdhOIu/ws7dcCEJCo0M8xiN0cs+5YKCcQodsDFX/WYkYK1i1b7pUVnAjagNEun9QE4iTZOrixclNH4kUvM4TWd59/ugteHpM757f6h5loxSvCvq9TuNoymjYm9ux2DB6IqcmFcHVEUsq+btZfhmn5yJQs1lPB9kVAP29QDJJdDTB7BHQ9fZFnMGIWsH+86hAkQU8kHWafhNkmdTXbt8wvlfCBdbP400bS3VVEq7KaHpBY4l8xgSTsOEW6h+EIhrkGoO4p/0iYkCDbi19dbegjSJeEzuT5vItD6OKbbHAKLJ8h3/eYV6QQCywLXAiyIdu3gYDUlQZNfCfBCtBVwb8WYN4X1lktKE4V5ejDeYSRaX2xzoCa0J2GNqTYodwqPFHzr+WV5XobDXoAeYAUpq82/LbF/yH16gg+aLw6jMnfjblF9xEK7rl3iUEgo1dA4jQdejjLVlrbFIVuyaiLhhA4KKyPC1Hlrff3/KF+JIRhUebb4hFxkaHTwLTWw4WBgErjdgiBsbV5xMWpGzIUYc8/4BmQmtZNDmRSeXi7ee7iCm0xl0KM6S9pvTf5DrgxTVmYxkKLsC0+zf1eG/WNukW7dTavDonVqyU2IZTV3s59yJTiwe35z4t2YeAlAsMxjOLu7fmOsZbiLDkTlwI4fGHqr9cqpV/hG/V494=
