language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install:
- pip install -e .
script: py.test --verbose --capture=no
env:
  global:
  - secure: Nl0jw7OMP3mXQo3QKDyqfERHj14JED4ZKX1ikV9ypr1zk81YWGQVK8k2kM2aqoUN22jPIiJc5F7pPwrKdQBb1CLsD71YuEgQZJFD4SVEejtzqMkGim5BlFKjCxTJFTGv95ve9iuOXbtULO7q5lecJZHOGXhrkZAzOsfdMsWgQUrngWpvW2rxSBO6AsHWvPr6sJ3Yqs1ZNuFJ4J222jPTUfvDdahSWzd+G6EEReyiFjA2TiQl7W5u7UaC4JK3QbU7c+7LNploPKq8/vPuhcuG7bMB9ueO9Yvfzf6NIXSLCC12j14F9PDjatd83u6gbzf9+air9ZxCqGxU9D+NvJ8R0J5Vk7lg1FAzCzQIW5Dog27gKKf/FQsir6UHGAZxZ3Eth6XgQ1/FKnf6oQKPZpvGT8QzTjqDgRs8Hh1ldm+NFEoJb5iqi9CBvGwOH3aG426ru5QBkhytBLTykQI1hj7wVP6n7AHbBo6RGCnUeaPmMRvPKKI3UqYXvXkU/KW4sA5h82CvKa8Q5iOntXP5/wwp1i3/+9TcMhQF/Vu4II7dDCVjdGQ02uB/pNLgstqcDKhayGxAEr/8QDdXGn+l78XJQA2qhvZSSdQGjD8peYabWbnMaGrHHjsKY6yTpDRvtcVpyn9dvdO6NfZ5OWybVNv43Vns8UA5Qg2MsM63TdgdNZc=
  - secure: b5xbeT3RDM0WT5iDW4TONobP9t+nSUpv0JKFkeuQ6Z2CQw6l6Ab6a9f/ktE2Af/N/WCM7tWiKGOc1G86+9nvpwVkgtCE2ObZLctMW9KWKFUibgx3r1hiwx8fezVbVPyOsD6tdNe1ZbqGNSUiUuqkwWM5q13I3p38YH4p8PS0Pa1uxCvsRv/1jxfv1LLRkllnwmAqVov2N1eWP9WuAMwznrE62utPwZhdUorJbM0EZoY22Si2yPNH8g+hZ7mpoO46f6ypP2lBmoJe1ElHgXx418kodENrVUZvchiWLiybkdhWmeCcmg3RlKqHukRDoV7o8jDCxqVQLS7V5qzCF75kKQVZI9k5q5H9Kz8RNRiJoZpryviH0+6uVOd8IH2AVt1FZjWNDw84gi7pB6LKiQHs6q83boGKLb94X8PtSEKcpLdeF0+DGdsVOUVE1lAtXzjaEMvRAstTeUscJQgkwgSK/G+aAGxRltDxH7v0iGs/Jn7Ee3mhsp3U69ZLCK2NLqInJ/ZyTEzq20ox2gu//4/0SuB9UPhXPwtI+wO7vEsZDF95VXGO25FPNKVNwPrlwwj/ba2e2dkqEsUesypPTSZb53jGw4FxR6Vwpn2x2Cm6J5wPDfCSxr9HDNJH+lMl6AbLAYPkacT1A/hGrBnoYH/C2nmNoiSJrLmE2gmzSYQkRj8=
